services:
  app:
    image: node:18.15.0
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/node/app
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    expose:
      - 3000
    command: "npm run dev"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: super
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      # Uncomment this if you want the DB to stop erasing data when bringing the stack down
      # - db:/var/lib/mysql
